[workspace]

members = [
  "cmd",
  "container",
  "container_api",
  "core_api_c_binding",
  "core",
  "core/src/nucleus/actions/wasm-test",
  "container_api/wasm-test",
  "hdk-rust/wasm-test",
  "wasm_utils/wasm-test/integration-test",
  "dna_c_binding",
  "hdk-rust",
  "net",
  "net_connection",
  "net_ipc",
  "test_bin",
]
exclude = ["test_utils"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
