[workspace]

members = [
  "cas_implementations",
  "cmd",
  "container",
  "container_api",
  "container_api/wasm-test",
  "core",
  "core/src/nucleus/actions/wasm-test",
  "core_api_c_binding",
  "core_types",
  "core_types_derive",
  "dna_c_binding",
  "hdk-rust",
  "hdk-rust/wasm-test",
  "net",
  "net_connection",
  "net_ipc",
  "test_bin",
  "test_utils",
  "wasm_utils",
  "wasm_utils/wasm-test/integration-test",
]
# exclude = ["test_utils"]

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
