bridges = []
[[agents]]
id = "test agent 1"
key_file = "holo_tester.key"
name = "Holo Tester 1"
public_address = "HoloTester1-----------------------------------------------------------------------AAACZp4xHB"

[[dnas]]
file = "example-config/app_spec.hcpkg"
hash = "Qm328wyq38924y"
id = "app spec rust"

[[dnas]]
file = "/home/zo-el/Downloads/holofuelv5.hcpkg"
hash = "QmSFFbDHUmhSWP8pA3Z63pN4hqqgg91c3At9E4hucfVmSn"
id = "holofuelv4.hcpkg"

[[instances]]
agent = "test agent 1"
dna = "holofuelv4.hcpkg"
id = "holofuelv4.hcpkg instance"

[instances.storage]
path = "example-config/tmp-storage"
type = "file"

[[interfaces]]
admin = true
id = "websocket interface"

[[interfaces.instances]]
id = "holofuelv4.hcpkg instance"

[interfaces.driver]
port = 3000
type = "websocket"

[[interfaces]]
admin = true
id = "http interface"

[[interfaces.instances]]
id = "holofuelv4.hcpkg instance"


[interfaces.driver]
port = 4000
type = "http"

[logger]
type = "debug"
[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[[logger.rules.rules]]
exclude = false
pattern = ".*"
